In [1]:
import numpy as np

In [2]:
a=np.array([11,22,33,44,55])

In [3]:
print(a)

[11 22 33 44 55]


In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [7]:
b=np.array([[11,22,33,44,55],[1,2,3,4,5]])

In [8]:
print(b)

[[11 22 33 44 55]
 [ 1  2  3  4  5]]


In [9]:
print(type(b))

<class 'numpy.ndarray'>


In [18]:
c=np.array([22,44,55,77], complex)

In [19]:
print(c)

[22.+0.j 44.+0.j 55.+0.j 77.+0.j]


In [20]:
print(c.ndim)

1


In [13]:
print(a.ndim)

1


In [14]:
print(b.ndim)

2


In [21]:
print(c.itemsize)

16


In [22]:
print(b.itemsize)

4


In [17]:
print(a.itemsize)

4


In [23]:
print(a.dtype)

int32


In [24]:
print(a.size)

5


In [25]:
print(b.dtype)

int32


In [26]:
print(b.size)

10


In [27]:
print(a.shape)

(5,)


In [28]:
print(b)

[[11 22 33 44 55]
 [ 1  2  3  4  5]]


In [29]:
print(b.dtype)

int32


In [30]:
print(b.size)

10


In [31]:
print(b.shape)

(2, 5)


## Reshaping the array

In [32]:
myarray=np.array([[11,22,33,44],[1,2,3,4],[11,22,33,44]])

In [33]:
print(myarray)

[[11 22 33 44]
 [ 1  2  3  4]
 [11 22 33 44]]


In [34]:
print(myarray.shape)

(3, 4)


In [35]:
myarray2=myarray.reshape(4,3)

In [36]:
print(myarray2)

[[11 22 33]
 [44  1  2]
 [ 3  4 11]
 [22 33 44]]


In [37]:
print(myarray)

[[11 22 33 44]
 [ 1  2  3  4]
 [11 22 33 44]]


In [38]:
print(myarray[0,1])

22


In [39]:
print(myarray[1,1])

2


In [40]:
print(myarray[2,1])

22


In [42]:
print(myarray[0,3])

44


## Arthmatic operations for array 

In [43]:
myarray3=np.array([[11,22,33,44],[1,2,3,4],[11,22,33,44]])

In [44]:
myarray4=np.array([[13,14,15,16],[1,2,3,4],[11,22,33,44]])

In [45]:
print(myarray3*myarray4)

[[ 143  308  495  704]
 [   1    4    9   16]
 [ 121  484 1089 1936]]


In [46]:
print(myarray3+myarray4)

[[24 36 48 60]
 [ 2  4  6  8]
 [22 44 66 88]]


In [47]:
print(np.hstack((myarray3,myarray4)) )

[[11 22 33 44 13 14 15 16]
 [ 1  2  3  4  1  2  3  4]
 [11 22 33 44 11 22 33 44]]


In [48]:
print(np.vstack((myarray3,myarray4)) )

[[11 22 33 44]
 [ 1  2  3  4]
 [11 22 33 44]
 [13 14 15 16]
 [ 1  2  3  4]
 [11 22 33 44]]
