In [1]:
import numpy as np

In [2]:
myarray=[0.11,1.22,8.44,4.55]

In [3]:
myarray

[0.11, 1.22, 8.44, 4.55]

In [4]:
myarray2=np.ceil(myarray)

In [5]:
myarray2

array([1., 2., 9., 5.])

In [6]:
myarray3=[100.2999,22.8,54.75443,788.5555]

In [7]:
myarray3

[100.2999, 22.8, 54.75443, 788.5555]

In [8]:
myarray4=np.ceil(myarray3)

In [9]:
myarray4

array([101.,  23.,  55., 789.])

In [17]:
myarray5=[1.9999,2.8999,5.7665,78.798]

In [18]:
myarray5

[1.9999, 2.8999, 5.7665, 78.798]

In [19]:
myarray6=np.fix(myarray5)

In [13]:
myarray6

array([1., 2., 5., 7.])

In [21]:
myarray7=np.floor(myarray5)

In [22]:
myarray7

array([ 1.,  2.,  5., 78.])

In [23]:
myarray7

array([ 1.,  2.,  5., 78.])

In [33]:
int_array=[12.6,51.55,41.999, 10.888]

In [34]:
int_array2=[12.1,51.055,41.2999, 10.4888]

In [35]:
myarray_total=np.rint(int_array)

In [36]:
myarray_total2=np.rint(int_array2)

In [37]:
int_array

[12.6, 51.55, 41.999, 10.888]

In [38]:
myarray_total

array([13., 52., 42., 11.])

In [39]:
int_array2

[12.1, 51.055, 41.2999, 10.4888]

In [40]:
myarray_total2

array([12., 51., 41., 10.])

In [45]:
import numpy.matlib

In [46]:
myeyearray=np.matlib.eye(4,  k=0 , dtype = float)

In [47]:
myeyearray

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [48]:
myeyearray=np.matlib.eye(5,  k=0 , dtype = int)

In [49]:
myeyearray

matrix([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])

In [50]:
myeyearray=np.matlib.identity(5,  int)

In [51]:
myeyearray

matrix([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])

In [52]:
myeyearray=np.matlib.identity(4)

In [53]:
myeyearray

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])