In [1]:
import numpy as np 

In [29]:
employee_info=[('name','S10'),('salary','f8'),('age','i8')]

In [33]:
employee_info

[('name', 'S10'), ('salary', 'f8'), ('age', 'i8')]

In [34]:
employees_staff=np.zeros((3),dtype=employee_info)

In [35]:
employees_staff

array([(b'', 0., 0), (b'', 0., 0), (b'', 0., 0)],
      dtype=[('name', 'S10'), ('salary', '<f8'), ('age', '<i8')])

In [49]:
employees_staff[2]=("Ahmed", 3000, 25)

In [50]:
employees_staff[1]=("Muhmmad", 6000, 26)

In [51]:
employees_staff

array([(b'',    0.,  0), (b'Muhmmad', 6000., 26), (b'Ahmed', 3000., 25)],
      dtype=[('name', 'S10'), ('salary', '<f8'), ('age', '<i8')])

In [52]:
employees_staff[0:]

array([(b'',    0.,  0), (b'Muhmmad', 6000., 26), (b'Ahmed', 3000., 25)],
      dtype=[('name', 'S10'), ('salary', '<f8'), ('age', '<i8')])

In [53]:
employees_staff[1:]

array([(b'Muhmmad', 6000., 26), (b'Ahmed', 3000., 25)],
      dtype=[('name', 'S10'), ('salary', '<f8'), ('age', '<i8')])

In [54]:
employees_staff[2:]

array([(b'Ahmed', 3000., 25)],
      dtype=[('name', 'S10'), ('salary', '<f8'), ('age', '<i8')])

In [55]:
salary=employees_staff['salary']

In [56]:
age=employees_staff['age']

In [57]:
add_salary=salary+2000

In [58]:
add_salary

array([2000., 8000., 5000.])

In [59]:
age

array([ 0, 26, 25], dtype=int64)

In [60]:
add_age=age+3

In [61]:
add_age

array([ 3, 29, 28], dtype=int64)

In [62]:
employees_staff

array([(b'',    0.,  0), (b'Muhmmad', 6000., 26), (b'Ahmed', 3000., 25)],
      dtype=[('name', 'S10'), ('salary', '<f8'), ('age', '<i8')])

In [63]:
all_employees=np.zeros((4,3,2),dtype=employee_info)

In [64]:
all_employees

array([[[(b'', 0., 0), (b'', 0., 0)],
        [(b'', 0., 0), (b'', 0., 0)],
        [(b'', 0., 0), (b'', 0., 0)]],

       [[(b'', 0., 0), (b'', 0., 0)],
        [(b'', 0., 0), (b'', 0., 0)],
        [(b'', 0., 0), (b'', 0., 0)]],

       [[(b'', 0., 0), (b'', 0., 0)],
        [(b'', 0., 0), (b'', 0., 0)],
        [(b'', 0., 0), (b'', 0., 0)]],

       [[(b'', 0., 0), (b'', 0., 0)],
        [(b'', 0., 0), (b'', 0., 0)],
        [(b'', 0., 0), (b'', 0., 0)]]],
      dtype=[('name', 'S10'), ('salary', '<f8'), ('age', '<i8')])

In [65]:
all_employees['name']

array([[[b'', b''],
        [b'', b''],
        [b'', b'']],

       [[b'', b''],
        [b'', b''],
        [b'', b'']],

       [[b'', b''],
        [b'', b''],
        [b'', b'']],

       [[b'', b''],
        [b'', b''],
        [b'', b'']]], dtype='|S10')

In [66]:
all_employees['age']

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]], dtype=int64)

In [67]:
all_employees['salary']

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [68]:
all_employees

array([[[(b'', 0., 0), (b'', 0., 0)],
        [(b'', 0., 0), (b'', 0., 0)],
        [(b'', 0., 0), (b'', 0., 0)]],

       [[(b'', 0., 0), (b'', 0., 0)],
        [(b'', 0., 0), (b'', 0., 0)],
        [(b'', 0., 0), (b'', 0., 0)]],

       [[(b'', 0., 0), (b'', 0., 0)],
        [(b'', 0., 0), (b'', 0., 0)],
        [(b'', 0., 0), (b'', 0., 0)]],

       [[(b'', 0., 0), (b'', 0., 0)],
        [(b'', 0., 0), (b'', 0., 0)],
        [(b'', 0., 0), (b'', 0., 0)]]],
      dtype=[('name', 'S10'), ('salary', '<f8'), ('age', '<i8')])

In [69]:
all_employees[0,0,1]=('Ahmed',3000,25)

In [70]:
all_employees

array([[[(b'',    0.,  0), (b'Ahmed', 3000., 25)],
        [(b'',    0.,  0), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)]],

       [[(b'',    0.,  0), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)]],

       [[(b'',    0.,  0), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)]],

       [[(b'',    0.,  0), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)]]],
      dtype=[('name', 'S10'), ('salary', '<f8'), ('age', '<i8')])

In [71]:
all_employees[1,1,0]=('Adnan',4000,20)

In [72]:
all_employees

array([[[(b'',    0.,  0), (b'Ahmed', 3000., 25)],
        [(b'',    0.,  0), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)]],

       [[(b'',    0.,  0), (b'',    0.,  0)],
        [(b'Adnan', 4000., 20), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)]],

       [[(b'',    0.,  0), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)]],

       [[(b'',    0.,  0), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)]]],
      dtype=[('name', 'S10'), ('salary', '<f8'), ('age', '<i8')])

In [73]:
all_employees[3,0,1]=('Muhmmed',5000,50)

In [74]:
all_employees

array([[[(b'',    0.,  0), (b'Ahmed', 3000., 25)],
        [(b'',    0.,  0), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)]],

       [[(b'',    0.,  0), (b'',    0.,  0)],
        [(b'Adnan', 4000., 20), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)]],

       [[(b'',    0.,  0), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)]],

       [[(b'',    0.,  0), (b'Muhmmed', 5000., 50)],
        [(b'',    0.,  0), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)]]],
      dtype=[('name', 'S10'), ('salary', '<f8'), ('age', '<i8')])

In [75]:
all_employees[2,0,0]=('Muhmmed',9000,43)

In [76]:
all_employees

array([[[(b'',    0.,  0), (b'Ahmed', 3000., 25)],
        [(b'',    0.,  0), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)]],

       [[(b'',    0.,  0), (b'',    0.,  0)],
        [(b'Adnan', 4000., 20), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)]],

       [[(b'Muhmmed', 9000., 43), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)]],

       [[(b'',    0.,  0), (b'Muhmmed', 5000., 50)],
        [(b'',    0.,  0), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)]]],
      dtype=[('name', 'S10'), ('salary', '<f8'), ('age', '<i8')])

In [77]:
all_employees['name']

array([[[b'', b'Ahmed'],
        [b'', b''],
        [b'', b'']],

       [[b'', b''],
        [b'Adnan', b''],
        [b'', b'']],

       [[b'Muhmmed', b''],
        [b'', b''],
        [b'', b'']],

       [[b'', b'Muhmmed'],
        [b'', b''],
        [b'', b'']]], dtype='|S10')

In [78]:
all_employees['age']

array([[[ 0, 25],
        [ 0,  0],
        [ 0,  0]],

       [[ 0,  0],
        [20,  0],
        [ 0,  0]],

       [[43,  0],
        [ 0,  0],
        [ 0,  0]],

       [[ 0, 50],
        [ 0,  0],
        [ 0,  0]]], dtype=int64)

In [79]:
all_employees['salary']

array([[[   0., 3000.],
        [   0.,    0.],
        [   0.,    0.]],

       [[   0.,    0.],
        [4000.,    0.],
        [   0.,    0.]],

       [[9000.,    0.],
        [   0.,    0.],
        [   0.,    0.]],

       [[   0., 5000.],
        [   0.,    0.],
        [   0.,    0.]]])

In [80]:
all_employees[['name', 'age']]

array([[[(b'',  0), (b'Ahmed', 25)],
        [(b'',  0), (b'',  0)],
        [(b'',  0), (b'',  0)]],

       [[(b'',  0), (b'',  0)],
        [(b'Adnan', 20), (b'',  0)],
        [(b'',  0), (b'',  0)]],

       [[(b'Muhmmed', 43), (b'',  0)],
        [(b'',  0), (b'',  0)],
        [(b'',  0), (b'',  0)]],

       [[(b'',  0), (b'Muhmmed', 50)],
        [(b'',  0), (b'',  0)],
        [(b'',  0), (b'',  0)]]],
      dtype={'names':['name','age'], 'formats':['S10','<i8'], 'offsets':[0,18], 'itemsize':26})

In [ ]:
all_employees[['name', 'salary']]